### PR TITLE
Add Holiday "Maria Empfaengnis (AT)" and "Nationalfeiertag (AT)"

### PR DESCRIPTION
**Pull request by mgeramb**
This is the PR for preparing to add holiday "Maria Empfängnis" 8.12 and "Nationalfeiertag" 26.10 for Austria.

### CODE REVIEW

**Comment by mumpf** [comment]
Hi,

I will include the holidays you mentioned, but there will be a slight change. To be compatible to previous versions, a renumbering of the holidays in ETS ist not possible. So the new holidays will get the numbers 30 and 31, even if their order in the list will be by date.

Background: Logicmodule returns the holiday index as the current holiday. I have for example some logic, which checks for Sylvester, which ist (currently) holiday 29. If we would introduce new holidays renumbering the old onex, Sylvester would become 31 and would invalidate existing logics after update.

You don't need to correct anything, I'll take care. I will keep this PR open until all work is finished. 

Regards,
Waldemar

**Comment by mgeramb** [comment]
> Hi,
> 
> I will include the holidays you mentioned, but there will be a slight change. To be compatible to previous versions, a renumbering of the holidays in ETS ist not possible. So the new holidays will get the numbers 30 and 31, even if their order in the list will be by date.
> 
> Background: Logicmodule returns the holiday index as the current holiday. I have for example some logic, which checks for Sylvester, which ist (currently) holiday 29. If we would introduce new holidays renumbering the old onex, Sylvester would become 31 and would invalidate existing logics after update.
> 
> You don't need to correct anything, I'll take care. I will keep this PR open until all work is finished.
> 
> Regards, Waldemar
Hi Waldemar,

My PR should already be downward compatible. The new holidays are already numbered with 30 and 31. Only the update of the screenshoot in the documentation is not yet updated.

Best, Michael

**Comment by mumpf** [comment]
Hi Michael,

today I will merge your pull request. Just to ensure, that I do not overlook again something: The place above with the 2 Holidays added is fine. What I am missing: In Timer.h you set the counter to 31 and not 32. Is this just a bug or by intention? You don't need to correct this, I will do, but I ask just to be sure...

Regards,
Waldemar

**Comment by mgeramb** [comment]
Hi Waldemar,
sorry, you are right, I forgot to check in these two files: https://github.com/OpenKNX/OAM-LogicModule/pull/2
Best, Michael

**Pull request merged**
